version: '3'
services:
  db:
    container_name: pokebuild-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: pokebuildmaker
    ports:
      - "4000:4000"
    volumes:
      - ./Database/:/docker-entrypoint-initdb.d/

  backend:
    container_name: pokebuild-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: apidb
      DATABASE_USER: root
      DATABASE_PASSWORD: 1